### PR TITLE
[WIP] Version 0.6

### PR DESCRIPTION
**Pull request by neongreen**

### CODE REVIEW

**Comment by brandonhamilton** [comment]
This is now building with stackage nightly (ghc-8.4.1)

**Comment by neongreen** [comment]
@brandonhamilton thanks! I haven't forgotten about this PR, but I'm in the process of preparing a major release (I want to run doctests and fix them all, remove the `double-conversion` dependency, etc). It should be done soon.

**Comment by neongreen** [comment]
Some doctests are failing:

```
### Failure in /home/yom/code/fmt/lib/Fmt.hs:999: expression `listF' floatF [1e-6,9e-7]'
expected: "[0.000001, 9e-7]"
 but got: "[1.0e-6, 9.0e-7]"

### Failure in /home/yom/code/fmt/lib/Fmt.hs:1024: expression `listF' (precF 3) [1e-5,1e-6,1e-7]'
expected: "[0.0000100, 0.00000100, 1.00e-7]"
 but got: "[1.000e-5, 1.000e-6, 1.000e-7]"

### Failure in /home/yom/code/fmt/lib/Fmt/Time.hs:46: expression `diffF False t    -- time period'
expected: "3 seconds"
 but got: 
          <interactive>:436:1: error:
              • No instance for (RealFrac ZonedTime)
                  arising from a use of ‘diffF’
              • In the expression: diffF False t
                In an equation for ‘it’: it = diffF False t
```

Some tests are also failing:

```
  tests/Main.hs:155:5: 
  1) formatters.floating-point precF
       expected: "1.3"
        but got: "1.30"
```

So, the behavior of `precF` and `floatF` has changed (or perhaps `floatF` was always like that). I'll investigate it tomorrow, if nobody does that sooner.

**Comment by neongreen** [comment]
If Travis doesn't pass after https://github.com/chrisdone/formatting/pull/39 is merged, I'll just fix it later.

**Pull request merged**
